include:
  - local: '/templates/.gitlab-ci-apax-docker.yml'

stages:
  - deliver
  - publish

Delivering:
  stage: deliver
  script:
    - 'bash "$SCRIPTS_DIR/ci-scripts/deliver-sdk-projects.sh"'
  artifacts:
    paths:
      - '*/*.apax.tgz'
    expire_in: 30 days
  only:
    - tags

Publishing:
  dependencies:
    - Delivering
  stage: publish
  script:
    - 'bash "$SCRIPTS_DIR/ci-scripts/publish-sdk-projects.sh"'
  only:
    - tags
