include:
  - local: '/templates/.gitlab-ci-apax-docker.yml'

stages:
  - test
  - deliver
  - publish

Testing:
  stage: test
  script:
    - 'bash "$SCRIPTS_DIR/ci-scripts/test-dotnet-projects.sh"'

Delivering:
  dependencies:
    - Testing
  stage: deliver
  script:
    - 'bash "$SCRIPTS_DIR/ci-scripts/deliver-dotnet-projects.sh"'
  artifacts:
    paths:
      - '**/*.apax.tgz'
    expire_in: 30 days
  only:
    - tags

Publishing:
  dependencies:
    - Delivering
  stage: publish
  script:
    - 'bash "$SCRIPTS_DIR/ci-scripts/publish-dotnet-projects.sh"'
  only:
    - tags
